api:
  insecure: true
  dashboard: true
log:
  level: debug
providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    directory: /etc/traefik-dynamic
    watch: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443